### ISSUE TITLE
Installing extra conda packages

### ISSUE THREAD

**Issue by eric-czech** [dask/dask-cloudprovider#167]
Does cloudprovider have any analog to the `EXTRA_[CONDA|APT|PIP]_PACKAGES` env vars that dask-kubernetes installs into the docker containers for schedulers/workers (i.e. https://github.com/dask/helm-chart/blob/9abe7b58ec2277aa3d9e4d06e1623b7345f776fa/dask/values.yaml#L61-L66)?

It didn't look like it at a glance at the code but I wanted to be sure.  Has this feature been requested before?

**Comment by eric-czech** [comment]
Oh I see, they're used in the entrypoint script for the image.  Is there a way then to set arbitrary environment variables for the VMs created by cloudprovider?

**Comment by jacobtomlinson** [comment]
The short answer for your use case is yes, you're looking for the `env_vars` option in `GCPCluster`.

https://cloudprovider.dask.org/en/latest/gcp.html#dask_cloudprovider.gcp.GCPCluster

---

The longer answer for others who discover this issue is that implementation depends on the cluster manager. 

The `EXTRA_[CONDA|APT|PIP]_PACKAGES` environment variables are a feature of the [Dask Docker image](https://github.com/dask/dask-docker). If you populate those environment variables in the Docker image packages will be installed via `conda/pip/apt` when the container starts.

Most cluster managers in this package today use Docker at some level. And the default Docker image will be the official Dask one. Most cluster managers also allow setting of arbitrary environment variables, but not necessarily consistently. So it's best to refer to the doc page for your specific cluster manager.

If you choose to use a custom Docker image then you would need to implement this feature yourself, either by basing off the official image or replicating what the [prepare script](https://github.com/dask/dask-docker/blob/master/notebook/prepare.sh) does. The [RAPIDS docker images](https://hub.docker.com/r/rapidsai/rapidsai/) support this for example because we have a similar prepare script.

**Comment by jacobtomlinson** [comment]
> is there any reason they couldn't come from environment variables in the client process

This is interesting, I hadn't considered that.

> or cloudprovider.yaml?

See the conversation in #169

**Comment by jacobtomlinson** [comment]
I think I'll close this issue now as the initial question has been answered. But it would be good to continue the discussion around making enhancements in #169.
