### ISSUE TITLE
create resource group and required resources for AzureVMCluster

### ISSUE THREAD

**Issue by lostmygithubaccount** [dask/dask-cloudprovider#190]
rather than requiring the user to create a resource group, vnet, security group, and set it up correctly,  can this be done by default for the user? this would also eliminate #188 as all resources could be created in the same location by `dask-cloudprovider`

so, this would now work:

```console
az login
az account set -s SUBSCRIPTION_ID
```

```python
from dask_cloudprovider.azure import AzureVMCluster
from distributed import Client

cluster = AzureVMCluster() # nothing required
cluster2 = AzureVMCluster(location="southcentralus") # all resources created in this location

c = Client(cluster)
c
```

**Comment by jacobtomlinson** [comment]
I would be happy to see this. 

I think I was worried that this may be overstepping. In the AWS `FargateCluster` class we go to great lengths to pre-create all resources for people. But we get a reasonable amount of feedback that default cluster creation fails because folks do not have permission to create such substantial resources.

But perhaps there is a case for both.
