### ISSUE TITLE
How to avoid mismatched Fargate client/scheduler versions?

### ISSUE THREAD

**Issue by rsignell-usgs** [dask/dask-cloudprovider#55]
I'm trying to create a FargateCluster from SageMaker, where I've created a custom conda environment.    But I'm not sure how to ensure that the workers in the FargateCluster get the same versions or blosc, distributed and numpy that my custom env has.     

How best to avoid the following?
```python
from dask_cloudprovider import FargateCluster
from dask.distributed import Client
client = Client(cluster)
```
is producing
```python-traceback
/home/ec2-user/SageMaker/myenvs/pangeo/lib/python3.8/site-packages/distributed/client.py:1074: VersionMismatchWarning: Mismatched versions found

blosc
+-------------------------+---------+
|                         | version |
+-------------------------+---------+
| client                  | 1.8.3   |
| scheduler               | 1.8.1   |
| tcp://172.31.5.60:43605 | 1.8.1   |
+-------------------------+---------+

distributed
+-------------------------+---------+
|                         | version |
+-------------------------+---------+
| client                  | 2.9.3   |
| scheduler               | 2.9.2   |
| tcp://172.31.5.60:43605 | 2.9.2   |
+-------------------------+---------+

numpy
+-------------------------+---------+
|                         | version |
+-------------------------+---------+
| client                  | 1.17.5  |
| scheduler               | 1.17.3  |
| tcp://172.31.5.60:43605 | 1.17.3  |
+-------------------------+---------+
  warnings.warn(version_module.VersionMismatchWarning(msg[0]["warning"]))
```

**Comment by rsignell-usgs** [comment]
Oh, I guess what I'm missing how to specify the packages I want in the Dask (here Fargate) workers.   When I try to run a real case, I'm getting:
```
distributed.worker - ERROR - No module named 'xarray'
```

**Comment by rsignell-usgs** [comment]
Okay egg-on-face here.  Just need to specify the container image.   Default is `daskdev/dask:latest`, so something like this should work:
  `FargateCluster(n_workers=1, image='pangeo/pangeo-esip'`)

**Comment by jacobtomlinson** [comment]
Glad you found a solution here @rsignell-usgs. This sounds like it could be a failing of the documentation, is there something we could improve there to help others better understand this in future?

**Comment by RichardScottOZ** [comment]
I don't think I have come across this in docs
e.g. when making a Fargate Cluster
the packages in your local environment [example] must match those in the container you make for x - there are probably passing references to clients, schedulers and workers etc?

These are the packages it is critical to match for this to work at all :- [list]
Any others you add should also match.

What happens if say, local environment doesn't have something that the cloud ones do?

**Comment by jacobtomlinson** [comment]
Typically with any Dask cluster we recommend that all environments match. You can sometimes get away with slight mismatches but we can't guarantee things will work in those cases so we don't recommend it. If your local environment has something that the worker does not and you try to use it in a task then the worker will die with an import error.

(General questions like this are probably more suited to the [Dask Community Forum](https://dask.discourse.group/) rather than a comment on a long closed issue.)
